steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/akc-crm', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/akc-crm']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'akc-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/akc-crm'
    - '--region'
    - 'us-east4'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'SUPABASE_URL=SUPABASE_URL:latest'
    - '--set-secrets'
    - 'SUPABASE_KEY=SUPABASE_KEY:latest'
    - '--set-secrets'
    - 'SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest'
    - '--set-secrets'
    - 'SUPABASE_DB_PASSWORD=SUPABASE_DB_PASSWORD:latest'
    - '--set-secrets'
    - 'FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/akc-crm' 