steps:
  # Build the container image with optimized caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/akc-crm', 
      '--cache-from', 
      'gcr.io/$PROJECT_ID/akc-crm:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/akc-crm']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'akc-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/akc-crm'
    - '--region'
    - 'us-east4'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'SUPABASE_URL=SUPABASE_URL:latest'
    - '--set-secrets'
    - 'SUPABASE_KEY=SUPABASE_KEY:latest'
    - '--set-secrets'
    - 'SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest'
    - '--set-secrets'
    - 'SUPABASE_DB_PASSWORD=SUPABASE_DB_PASSWORD:latest'
    - '--set-secrets'
    - 'FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest'
    - '--memory'
    - '512Mi'

  # Create a latest tag for future cache optimization
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/akc-crm', 'gcr.io/$PROJECT_ID/akc-crm:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/akc-crm:latest']

timeout: 1800s  # Set a 30-minute timeout instead of the default 10 minutes

images:
  - 'gcr.io/$PROJECT_ID/akc-crm' 
  - 'gcr.io/$PROJECT_ID/akc-crm:latest' 