name: Deploy to Cloud Run

on:
  push:
    branches:
      - deploy/cloud-run

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: akc-crm
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Build and deploy to Cloud Run
      run: |
        gcloud builds submit --config cloudbuild.yaml 